"""add user table

Revision ID: 85294fb0ff92
Revises: b1995f99bf70
Create Date: 2025-05-08 15:38:17.779718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85294fb0ff92'
down_revision = 'b1995f99bf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
